- README.md
> add theme-hao

- README.md
> add plugin-prismjs

- README.md
添加 halo-plugin-email 插件到社区列表中
```release-note
None
```
> Add halo-plugin-email

- README.md
Halo2.0 对 [vanilla-lazyload](https://github.com/verlok/vanilla-lazyload) 的集成
```release-note
None
```
> add plugin-lazyload

- README.md
https://github.com/liuzhihang/plugin-tocbot
```release-note
None
```
> add plugin-tocbot

- README.md
添加新主题 https://github.com/guqing/halo-theme-higan
```release-note
None
```
> feat: add new theme item for higan

- README.md
Halo 2.0 对 [pangu.js](https://github.com/vinta/pangu.js) 的集成，支持中英文、符号之间添加空格。
```release-note
None
```
> add plugin-pangu

- README.md
Updated plugin pixabay
```release-note
None
```
> Add plugin pixabay

- README.md
添加适配了 2.0 的 sakura 主题 https://github.com/LIlGG/halo-theme-sakura/tree/next
添加新插件 plugin-live2d https://github.com/LIlGG/plugin-live2d
```release-note
None
```
> add theme-sakura and plugin-live2d

- README.md
```release-note
增加社区主题 https://github.com/wan92hen/theme-terminal
```
> add theme-terminal

- README.md
添加 S3 协议对象存储插件，兼容大部分对象存储服务商
https://github.com/longjuan/halo-plugin-s3os
```release-note
None
```
> add halo-plugin-s3os

- README.md
添加 https://github.com/halo-sigs/plugin-bytemd 和 https://github.com/halo-sigs/plugin-stackedit 插件到插件列表。
/kind documentation
```release-note
None
```
> docs: add plugin-stackedit and plugin-bytemd

- README.md
添加主题[halo-theme-stack](https://github.com/jiewenhuang/halo-theme-stack) 到主题>社区列表
```release-note
None
```
> Add theme-stack to community theme list

- README.md
`halo-plugin-s3os` -> `plugin-s3`
```release-note
None
```
> rename to plugin-s3

- README.md
增加社区主题 https://github.com/liuchangfitcloud/theme-moderna
Thanks to bootstrapmade for provide free Html templates
```release-note
None
```
> add theme-moderna

- README.md
add plugin-uposs
仓库：https://github.com/AirboZH/plugin-uposs
可测试 JAR 包：https://github.com/AirboZH/plugin-uposs/releases/tag/Release-1.0
```release-note
None
```
> add plugin-uposs

- README.md
https://github.com/halo-sigs/plugin-feed
可以在这里下载测试：https://github.com/halo-sigs/plugin-feed/releases/tag/v1.1.0-beta.1
```release-note
None
```
> add plugin-feed

- README.md
一个Halo博客主题，Butterfly 🦋 适配  2.0 
```release-note
None
```
> add butterfly

- README.md
add theme-oranges  https://github.com/WuWenL0/halo-theme-oranges
```release-note
None
```
>  docs: add theme-oranges

- README.md
添加 https://github.com/f2ccloud/theme-ocean 到社区主题列表。
```release-note
None
```
> add theme-ocean

- README.md
添加 [plugin-oauth2](https://github.com/halo-sigs/plugin-oauth2) 插件到官方插件列表
测试插件地址：[plugin-oauth2-1.0.0-rc.1.jar](https://github.com/halo-sigs/plugin-oauth2/releases/download/v1.0.0-rc.1/plugin-oauth2-1.0.0-rc.1.jar)
```release-note
None
```
> feat: add oauth2 plugin

- README.md
添加 [plugin-moments](https://github.com/halo-sigs/plugin-moments) 瞬间管理插件以及 [plugin-photos](https://github.com/halo-sigs/plugin-photos) 图库管理插件 到官方插件列表
```release-note
None
```
> feat: add plugin-moments and plugin-photos

- README.md
增加一个使用 GitHub 做附件存储的插件
https://github.com/guicaiyue/plugin-githuboss
```release-note
None
```
> add plugin-githuboss

- README.md
增加一个 复制追加 插件
```release-note
None
```
> add plugin-copy-add

- README.md
增加一个使用 Gitee远程仓库作halo存储策略的插件
https://github.com/MartyAlien/plugin-giteeoss
```release-note
- 支持使用 Gitee 做附件存储
- 支持删除文件时可以不同步删除仓库
```
> add plugin-giteeoss

- README.md
添加 https://github.com/halo-sigs/plugin-katex 插件。
```release-note
None
```
> add plugin-katex

- README.md
新增主题 halo-theme-chirpy
```release-note
None
```
> Add halo-theme-chirpy

- README.md
https://github.com/Roozenlz/plugin-bilibili-bangumi
```release-note
None 
```
> add plugin-bilibili-bangumi

- README.md
see https://github.com/Roozenlz/halo-theme-aurora for more
```release-note
None
```
> add halo-theme-aurora

- README.md
> Update halo-theme-aurora url

- README.md
https://github.com/jiewenhuang/halo-theme-joe3.0
```release-note
None
```
> Add halo-theme-joe3.0

- README.md
add plugin halo-plugin-sitepush
https://github.com/Stonewuu/halo-plugin-sitepush
```release-note
None
```
> add plugin halo-plugin-sitepush

- README.md
修改评论、搜索、RSS、Sitemap 插件的仓库地址。目前这四个插件已经转移到 halo-dev 组织。
/kind documentation
```release-note
None
```
> chore: update some repos url

- README.md
添加 [obsidian-halo](https://github.com/halo-sigs/obsidian-halo) 到其他列表。
```release-note
None
```
> add obsidian-halo

- README.md
添加 [plugin-app-store](https://github.com/halo-dev/plugin-app-store) 到官方插件列表。
```release-note
None
```
> add plugin-app-store

- README.md
添加 [plugin-hybrid-edit-block](https://github.com/halo-sigs/plugin-hybrid-edit-block) 到官方插件列表。
```release-note
None
```
> add plugin-hybrid-edit-block

- README.md
添加 [halo-plugin-webp-cloud](https://github.com/webp-sh/halo-plugin-webp-cloud) 到社区插件列表
```release-note
None
```
> add halo-plugin-webp-cloud

- README.md
> add telegram-channel-publisher

- README.md
- 插件地址：
[halo-plugin-export-md](https://github.com/Lyn4ever29/halo-plugin-export-md)
- 功能：
导出文章为Markdown、Html文件并打包下载
- 注：
顺带帮忙上架到应用市场吧，谢谢
```release-note
None
```
> Add plugin halo-plugin-export-md

- README.md
- 插件地址:
[halo-plugin-vditor](https://github.com/justice2001/halo-plugin-vditor)
- 功能
为 Halo 添加 vditor 编辑器支持，支持所见即所得、即时渲染、分屏渲染三种渲染模式
> add halo-plugin-vditor

- README.md
Markdown 批量导出工具、开放式跨平台博客解决方案，随意组合写作平台(语雀/Notion/FlowUs/飞书)和博客平台(Hexo/Vitepress/Halo/Confluence/WordPress等)
Github：https://github.com/LetTTGACO/elog
Elog 文档：https://elog.1874.cool/
```release-note
None
```
> feat: 推荐 elog

- README.md
> add halo-plugin-webhook

- README.md
see https://github.com/terwer/siyuan-plugin-publisher
```release-note
None
```
> Add siyuan-plugin-publisher

- README.md
> Add plugin-notify-me

- README.md
https://github.com/Rainsheep/halo-plugin-meilisearch
```release-note
None
```
> add halo-plugin-meilisearch

- README.md
> add plugin-friends

- README.md
一款体现文字美感的极简主题 —— MeaWord
https://github.com/Meayair/Halo-Theme-MeaWord
```release-note
None
```
> Add Theme MeaWord

- README.md
增加社区主题：https://github.com/liuchangfitcloud/theme-mainroad
基于 Hogo 主题[Mainroad](https://github.com/Vimux/Mainroad)改造。
预览地址：https://www.wggznb.top/?preview-theme=theme-mainroad
> add theme-mainroad

- README.md
add theme about halo-theme-zero
> add theme zero

- README.md
add halo-theme-aircloud  
see https://github.com/bit15k/halo-theme-aircloud  
```
None
```
> add halo-theme-aircloud

- README.md
> add plugin-douban

- README.md
> add theme-material

- README.md
https://github.com/chengzhongxue/halo-theme-farallon
```release-note
None
```
> add theme-farallon

- README.md
辛苦审核人员。
添加了我的主题，并修改了上一行困困鱼复制粘贴忘改了的主题名字
```release-note
None
```
> add theme-heolink

- README.md
新增https://github.com/carolcoral/plugin-afdian 爱发电插件 麻烦同步到应用商店中
```release-note
None
```
> Add plugin afdian

- README.md
> add halo-theme-iemo

- README.md
将 [Twikoo](https://twikoo.js.org/) 评论系统集成到 Halo。
Repo: https://github.com/ichenhe/halo-twikoo
Live Example: https://chenhe.me/make-friends
请帮忙发布到应用商店。
**Preview**
```release-note
None
```
> add twikoo plugin

- README.md
新增主题 halo-theme-fresh
```release-note
None
```
> 新增主题 halo-theme-fresh

- README.md
>  add halo-theme-mcnav

- README.md
图床插件
对接多种图床服务，实现图片上传、删除等功能
```release-note
None
```
> add plugin plugin-picture-bed

- README.md
> add halo-theme-twentytwelve

- README.md
新增了 社区主题 halo-theme-hingle2.0 的链接与描述
```release-note
None
```
> Add theme halo-theme-hingle2.0

- README.md
> add halo-theme-hellopage

- README.md
麻烦上架到应用商店，谢谢！
```release-note
None
```
> 新增插件plugin-artalk

- README.md
> add theme-Mego

- README.md
因更改GitHub用户名，修改仓库地址，麻烦同步修改一下应用市场的地址
```
NONE
```
> update halo-plugin-typecho's repo

- README.md
https://github.com/zhheo/halo-plugin-postchat
```release-note
None
```
> Add halo-plugin-postchat

- README.md
添加 https://github.com/halo-sigs/plugin-editor-hyperlink-card 插件。
```release-note
None
```
> Add plugin-editor-hyperlink-card

- README.md
辛苦帮忙审批下，并发布到应用商店
```release-note
None
```
> add halo-theme-crux-4zero4

- README.md
add halo-plugin-colorless
```release-note
None
```
> Add halo-plugin-colorless

- README.md
This reverts commit e8f48433bbcfa39b0880d08fb44d8081a678ed41.
> Revert "Add halo-plugin-colorless (#112)"

- README.md
https://github.com/Anyexyz/theme-vcard4
```release-note
None
```
> add theme-vcard4

- README.md
https://github.com/bit15k/halo-theme-next
```release-note
None
```
> add halo-theme-next

- README.md
https://github.com/chengzhongxue/plugin-comment-migrate
```release-note
None
```
> add plugin-comment-migrate

- README.md
https://github.com/chengzhongxue/halo-theme-stellar
```release-note
None
```
> add halo-theme-stellar

- README.md
https://github.com/Aziteee/halo-theme-lapis
```release-note
None
```
> add halo-theme-lapis

- README.md
https://github.com/MagicBreeze/halo-theme-Ying
```release-note
None
```
> add halo-theme-Ying

- README.md
[https://github.com/luijp/theme-s1mp1e](https://github.com/luijp/theme-s1mp1e)
```release-note
None
```
> add halo-theme-s1mp1e

- README.md
浏览此页面的时候，点击这个超链接发现没有跳转，检查原始文档后补充遗失的链接
> fix: add lost link

- README.md
> add halo-plugin-summaraidGPT

- .github/pull_request_template.md
- README.md
> Add halo-theme-word

- README.md
> Add:halo-plugin-footprin

- README.md
[https://github.com/lyujp/halo-theme-kui-niu](https://github.com/lyujp/halo-theme-kui-niu)
```release-note
None
```
> add halo-theme-kui-niu

- README.md
https://github.com/chengzhongxue/plugin-pwa
https://github.com/chengzhongxue/flow-post
```release-note
None
两个插件
```
> Add plugin-pwa and flow-post

- README.md
https://github.com/Liksone/halo-theme-sora
```release-note
None
```
> add halo-theme-sora

- README.md
https://github.com/Idea-flow/theme-Ideaflow
```release-note
辛苦上架到halo应用市场一下,谢谢~
如果信息填写不对的地方,辛苦可以联系我一下,我及时调整 
邮箱:843145936@qq.com
```
> 增加theme-Ideaflow主题

- README.md
https://github.com/acanyo/halo-plugin-bingeWatching
```release-note
None
```
> add halo-plugin-bingeWatching

- README.md
https://github.com/acanyo/plugin-IndexNow
- [ - ] 上架到 [Halo 应用市场](https://www.halo.run/store/apps)。
```release-note
None
```
> add plugin-IndexNow

- README.md
https://github.com/acanyo/plugin-coverImage
```release-note
None
```
> add plugin-coverImage

- README.md
https://github.com/chengzhongxue/plugin-equipment
```release-note
None
```
> add plugin-equipment

- README.md
https://github.com/chengzhongxue/link-submit
```release-note
None
```
> Add link-submit

- README.md
https://github.com/Lentinel/plugin-Sakana-widget-Halo
```release-note
None
```
> add plugin-Sakana-widget-Halo

- README.md
https://github.com/acanyo/plugin-announcement
```release-note
None
```
> add plugin-announcement

- README.md
https://github.com/ShiinaKin/halo-plugin-bangumi-data
```release-note
None
```
> add plugin-bangumi-data

- README.md
add plugin-editor-theme-page
https://github.com/chengzhongxue/plugin-editor-theme-page
```release-note
None
```
> add plugin-editor-theme-page

- README.md
https://github.com/Erzbir/halo-theme-terminal
```release-note
None
```
> add halo-theme-terminal-ez

- README.md
> add halo-theme-vapor

- README.md
https://github.com/chengzhongxue/plugin-vote
```release-note
None
```
> add plugin-vote
